### ISSUE TITLE
Why does my application randomly take exactly 1 minute to execute a single SELECT statement?

### ISSUE THREAD

**Issue by dipens** [microsoft/msphpsql#1055]
**PHP Driver version or file name - 5.6.1**

**SQL Server version - 2012**

 **Client operating system - Ubuntu 18.04**

**PHP version - 7.3**

**Microsoft ODBC Driver version - 13**

**View schema**
```
SELECT P.*
FROM dbo.tblProjects P WITH(NOLOCK)
LEFT OUTER JOIN view_PJ_Status S WITH (NOLOCK) ON P.Pj_Status=S.Pj_Status  
LEFT OUTER JOIN dbo.view_Code_PjStage ST WITH(NOLOCK) ON P.Pj_Stage=St.Code_PjStage
LEFT OUTER JOIN dbo.W3viewPJActivationDate AD ON P.Pj_PK = AD.Pj_PK
LEFT OUTER JOIN dbo.tblCustomer C WITH (NOLOCK) ON P.Cust_PK = C.Cust_PK
LEFT OUTER JOIN dbo.tblTerms (NOLOCK) ON c.Term_PK = dbo.tblTerms.Term_PK 
LEFT OUTER JOIN dbo.tblEmployee CS (NOLOCK) ON C.Cust_SalesPerson = CS.Employ_PK
LEFT OUTER JOIN dbo.tblContacts SP (NOLOCK) on P.Pj_DesignerNum =SP.Con_PK 
LEFT OUTER JOIN tblContactsAddresses SPA WITH(NOLOCK) ON SP.con_pk = SPA.Con_PK AND TypeIndex='Bill To'
LEFT OUTER JOIN tblContacts BT WITH (NOLOCK) ON P.pj_attnCon_PK =BT.Con_PK  
LEFT OUTER JOIN tblContacts BL WITH (NOLOCK) ON P.Pj_Building_Con_PK =BL.Con_PK  
LEFT OUTER JOIN dbo.tblEmployee AS PM WITH (NOLOCK) ON P.Pj_AccountManager = PM.Employ_PK 
LEFT OUTER JOIN dbo.tblEmployee AS EST WITH (NOLOCK) ON P.Pj_SalesPerson = EST.Employ_PK 
LEFT OUTER JOIN dbo.tblEmployee AS CT WITH (NOLOCK) ON P.Pj_Contact = CT.Employ_PK
LEFT OUTER JOIN dbo.tblEmployee HWD WITH (NOLOCK) ON P.Pj_Coordinator = HWD.Employ_PK 
LEFT OUTER JOIN dbo.tblEmployee HME WITH(NOLOCK) ON P.Pj_HMEngineer = HME.Employ_PK
LEFT OUTER JOIN dbo.tblEmployee FUA WITH(NOLOCK) ON P.Pj_FollowUpAdmin = FUA.Employ_PK
LEFT OUTER JOIN (SELECT PJ_PK, MIN(Con_PK) AS PjR_ConPK From tblProjectsResources WITH(NOLOCK) WHERE PjR_Role=120  GROUP BY  PJ_PK) PHS ON P.Pj_PK = PHS.Pj_PK 
LEFT OUTER JOIN tblContacts PHSC WITH(NOLOCK) ON PHS.PjR_ConPK=PHSC.Con_PK 
WHERE P.TenantPK=SYSTEM_USER AND Pj_PK = 12345
GO
```
**Problem description**
The view above is just an example. But it happens on the simplest of queries. I have a simple form on Symfony 4.3.6 which is using Doctrine on Ubuntu 18.04. I am just migrating everything from freeTDS to msphpsql since they are the official drivers for MSSQL. The problem is that randomly, when users try to open a form, it takes exactly 1 minute to execute a select query. This only happens once in maybe 30-40 select statements. But its annoying to the users. There is no pattern so far that I have been able to detect. Hence for the lack of words, I am going to say its random. I was expecting maybe that could have been because of the code

```
-- network protocol: TCP/IP
set quoted_identifier on
set arithabort off
set numeric_roundabort off
set ansi_warnings on
set ansi_padding on
set ansi_nulls on
set concat_null_yields_null on
set cursor_close_on_commit off
set implicit_transactions off
set language us_english
set dateformat mdy
set datefirst 7
**set transaction isolation level read committed**
```
The above piece of code is run by the Driver/Doctrine/Symfony
The code `set transaction isolation level read committed` might be the source of my problem(not sure). The problem is I don't know how to even change this setting. Any guidance will be much appreciated.

**Expected behavior and actual behavior
Expected behavior**
Query should take less than 1 second to execute.
**Actual behavior**
Query should take exactly 1 minute to execute.
**Repro code or steps to reproduce**
Run a select statement.

**Comment by david-puglielli** [comment]
@dipens I would suggest running SQL Server Profiler to find out what might be taking so long on the server side. If you can't find anything with the profiler, it might be on the client side - try running a simple PHP script with multiple SELECTs and without Symfony or any other frameworks and see if the problem persists. If it does, try those queries using `sqlcmd` only.

**Comment by dipens** [comment]
I tried that.

Its the following query that's taking 1 minute.

```
-- network protocol: TCP/IP
set quoted_identifier on
set arithabort off
set numeric_roundabort off
set ansi_warnings on
set ansi_padding on
set ansi_nulls on
set concat_null_yields_null on
set cursor_close_on_commit off
set implicit_transactions off
set language us_english
set dateformat mdy
set datefirst 7
set transaction isolation level read committed
```

Weird thing is, it takes exactly 1 minute.

**Comment by dipens** [comment]
This query shouldn't take more than a second but surprisingly it takes more than a minute. I have attached the log as well.



RowNumber | EventClass | TextData | ApplicationName | NTUserName | LoginName | CPU | Reads | Writes | Duration | ClientProcessID | SPID | StartTime | EndTime | BinaryData
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
687 | 14 | -- network protocol: TCP/IP set quoted_identifier on set arithabort off set numeric_roundabort off set ansi_warnings on set ansi_padding on set ansi_nulls on set concat_null_yields_null on set cursor_close_on_commit off set implicit_transactions off set language us_english set dateformat mdy set datefirst 7 set transaction isolation level read committed | apache2 | NULL | tgrp | NULL | NULL | NULL | NULL | 4757 | 76 | 2019-11-07 15:40:48 | NULL | NULL
962 | 15 | NULL | apache2 | NULL | tgrp | 0 | 0 | 0 | 60196000 | 4757 | 76 | 2019-11-07 15:40:48 | 2019-11-07 15:41:48 | NULL


As you can see, the duration for the query that started at 2019-11-07 15:40:48 ended at 2019-11-07 15:41:48 and it took exactly 1 minute to execute this. The duration is also listed.

**Comment by david-puglielli** [comment]
I am not yet able to reproduce this. I notice that you are using ODBC driver 13 on Ubuntu 18.04, but ODBC driver 17 is required for Ubuntu 18.04 support. Can you try upgrading your ODBC driver, following the instructions [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)? If that is not possible, please tell us how you installed ODBC driver 13 so we can recreate your environment.

**Comment by dipens** [comment]
Sorry I must be going blind. The version is in fact 17.

**Comment by david-puglielli** [comment]
The transaction isolation level is set in the DSN, not in the option array. Construct the DSN and connect like so:
```
$dsn = "sqlsrv:server=myserver;TransactionIsolation=".PDO::SQLSRV_TXN_READ_UNCOMMITTED.";";
$dbh = new PDO($dsn, $user, $password,array(PDO::ATTR_TIMEOUT => 3600));
```
Note that `PDO::SQLSRV_TXN_READ_UNCOMMITTED` is a PHP constant while `$dsn` is a string, so it's concatenated for inclusion. Also note that the keyword is `TransactionIsolation`, and PDO::SQLSRV_TXN_READ_UNCOMMITTED is one of its possible values.

**Comment by dipens** [comment]
Thank you. It seems at least I can connect with the options I need. But now I get 

> Login timeout expired 

intermittently. I have checked #190 . I am using the IP address of the server to connect and not the named instance. I am also providing the port number, username and password accurately. 

I don't know what I am doing wrong here.

**Comment by david-puglielli** [comment]
How intermittently does it happen? There was an issue in ODBC driver 13 that caused intermittent timeouts, but it has been fixed. Do you by any chance have both version 13 and 17 of the ODBC driver on your system?

**Comment by dipens** [comment]
Couldn't find a pattern. Sometimes it did not happen at all. Once it happened at ~210 queries or 15 seconds. I did notice it happening when too many queries were run at the same time.

I think I only have 17 installed. Here is my config from /etc/odbcinst.ini.

```
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1
UsageCount=1
[ServerName]
Driver = FreeTDS
Server = ServerName.DomainName.local
Port = 1433
TDS_Version = 7.2
```

**Comment by david-puglielli** [comment]
Do you still have the original problem, that a particular SELECT query takes exactly one minute? Also, how many queries seem to be running when you get the `Login timeout expired` message?

**Comment by dipens** [comment]
Yes I still have the original problem. Its not an particular query. It happens on a lot of queries. 

Sorry I really tried to calculate but I could not find a specific pattern. Sometimes it runs over 200 queries without any problems. Sometimes, I can't even get past more than 20.

**Comment by david-puglielli** [comment]
These types of intermittent network issues are very difficult to track down, but there are a few things we can try. 
- Try running a bunch of SELECT queries with `sqlcmd` and see if the problem(s) continue
- If possible, try a different SQL Server instance
- If you have access to a Windows client, try these queries in Management Studio
- Capture a network trace with Wireshark

**Comment by dipens** [comment]
> - Try running a bunch of SELECT queries with sqlcmd and see if the problem(s) continue

Does not happen. Queries execute without any delay.

> - If possible, try a different SQL Server instance

This possibly might be our answer. We tried it with a different instance and the problem did not happen. We tried it with the same old SQL server but a different database. It choked up the entire DB including the production DB. We are thinking there is some config we have done on our old SQL server that's causing this. Is there any chance you know what config options we are missing on our Server?

> - If you have access to a Windows client, try these queries in Management Studio

No delays.

> - Capture a network trace with Wireshark

Didn't try this option yet.

**Comment by david-puglielli** [comment]
Is the different instance the same version of SQL Server as the problematic one?

**Comment by dipens** [comment]
Yes. They both have similar specs and version.

**Comment by david-puglielli** [comment]
So it's likely some kind of configuration issue on that particular instance, but I'm not sure yet what it might be. Have you tried with both sqlsrv and pdo_sqlsrv?

**Comment by dipens** [comment]
Yes I tried it. I got the same results.

**Comment by david-puglielli** [comment]
The best thing to do then is capture a network trace with Wireshark and attach it here. I wonder also if the server might simply be getting overloaded/running out of memory? Unlikely but possible.

**Comment by dipens** [comment]
[capture-output.pcap](https://drive.google.com/file/d/1ut7DDIYwc-yi7ZhyqMB7rhE4WQc8TJEF/view?usp=sharing). 

Sorry I am not familiar with WireShark so I tried my best to analyze and go through the traffic. I did manage to capture the issue in a Wireshark trace file. Some info that you will probably need.

- Client Machine IP address: 192.168.216.131
- Ubuntu Server IP: 192.168.212.207
- SQL Server IP: 192.168.212.50

Let me know if I can provide you with more info.

I tried running the query with no others users on the server and I still ran into it. The server is pretty new so I doubt its overloading or running out of memory. Let's see if this capture files helps you.

**Comment by v-chojas** [comment]
The capture is very useful to show what is happening, although specifying on which machine the capture was taken would've been even better. The query that appears to take 1 minute starts at frame 4876 and spans 4 packets. The sequence of events is

```
4876>seq 3471 ack 2988 len 4112 - 1st packet of query 
4877>seq 7583 ack 2988 len 4112 - 2nd packet of query
4878<seq 2988 ack 7583 len 0 - server acks 1st packet
4879>seq 11695 ack 2988 len 5792 - 3rd packet of query
4880>seq 17487 ack 2988 len 2017 - 4th and final packet of query
4881<seq 2988 ack 10479 len 0 - server acknowledges most of 2nd packet
4882<seq 2988 ack 11695 len 0 - server acknowledges rest of 2nd packet
4883<seq 2988 ack 11695 len 16 - MARS packet (not important for now, but appears to be lost)
4884>seq 19504 ack 2988 len 0 - client does not acknowledge packet above
4885<seq 3004 ack 11695 len 0 - server acks 11695 again, appears to have not received 4879 yet
4886>seq 19504 ack 2988 len 0 - client still does not see 4883
4887<seq 3004 ack 11695 len 0 - server asks for packet 4879 again...
4888<seq 3004 ack 11695 len 0 - ...and again...
4889<seq 3004 ack 11695 len 0 - ...and again...
4890<seq 3004 ack 13143 len 0 - server finally saw first part of 3rd packet...
4891<seq 3004 ack 19504 len 0 - ...and then the rest of it and the 4th packet
[server has received whole query and starts processing it]
4892<(window update, not important for now)
4893<seq 3004 ack 19504 len 16 - MARS packet (not important for now)
4894>seq 19504 ack 2988 len 0 - client still has not received 4883
4895<seq 3020 ack 19504 len 1448 - server starts sending result of query...
4896>seq 19504 ack 2988 len 0 - ...while client continues asking for 4883
4897<seq 4468 ack 19504 len 1448 - server continues sending result of query
4898>seq 19504 ack 2988 len 0 - client asks again for 4883
4899<seq 5916 ack 19504 len 1216 - server continues sending result of query
4900>seq 19504 ack 2988 len 0 - client asks again for 4883
4901<seq 7132 ack 19504 len 1448 - server continues sending result of query
4902>seq 19504 ack 2988 len 0 - client still hasn't received 4883 yet
4903<seq 8580 ack 19504 len 1448 - server continues sending result of query
4904>seq 19504 ack 2988 len 0 - client still hasn't received 4883 yet
4905<seq 10028 ack 19504 len 1216 - server continues sending result of query
4906>seq 19504 ack 2988 len 0 - client still hasn't received 4883 yet
4907<seq *2988* ack 19504 len 16 - server finally retransmits 4883...
4908>seq 19504 ack 2988 len 0 - ...but client has not seen it yet
4909<seq 11244 ack 19504 len 1448 - server continues with query
4910>seq 19504 ack 2988 len 0 - client still hasn't received 4883 yet
4911<seq 12692 ack 19504 len 880 - server sends final packet of results...
4912>seq 19504 ack 2988 len 0 - ...but client is still waiting for 4883
4936>seq *11695* ack 2988 len 1448 - client finally received 4885 ?
4937<seq 13572 ack 19504 len 0 - server tells client it already received up to 19504
[30 seconds elapse...]
5218>seq *19503* ack 2988 len 0 - client sends keep-alive
5219<seq 13572 ack 19504 len 0 - server's response to keep-alive
[30 seconds elapse...]
5431<seq *2988* ack 19504 len 16 - server retransmits 4883 again
5432<seq *3004* ack 19504 len 1432 - server retransmits 4893 and beginning of query results
5433>seq 19504 ack 4436 len 0 - client finally acknowledges their reception
5434<seq 4436 ack 19504 len 1448 - server continues retransmission
5435<seq 5884 ack 19504 len 1448 - ...and continues...
5436>seq 19504 ack 7332 len 0 - client continues acknowledgements
5437<seq 7332 ack 19504 len 1448
5438<seq 8780 ack 19504 len 1448
5439>seq 19504 ack 10228 len 0
5440<seq 10228 ack 19504 len 1448
5441<seq 11676 ack 19504 len 1448
5442>seq 19504 ack 13124 len 0
5443>seq 19504 ack 13124 len 16
5444<seq 13124 ack 19520 len 0
5445<seq 13124 ack 19520 len 448 - server finishes retransmission of query results
5446>seq 19520 ack 13572 len 61 - client sends sp_unprepare call
```

In other words, it appears you have a networking issue. Packets are getting lost/delayed and this causes TCP retransmissions, which happen after a certain timeout. I notice that the frame size from the client has some large ones (>1448, the standard Ethernet size) and that the client  appears to be a VMware VM; this thread may have more information on working around packet loss:

https://communities.vmware.com/thread/529014

You can also try to disable "jumbo frames" functionality in the client OS, because I suspect those excessively large packets may be contributing to the packet loss.

**Comment by dipens** [comment]
Ok so this was happening on this particular instance of SQL Server 2012. We did the following to fix it.
The old SQL Server 2012 was installed on Windows Server 2008. We reinstalled the SQL Server on Windows Server 2012 and this seemed to fix this issue. Still no idea as to what actually was the issue. But reinstalling seems to have fixed it.
